### PR TITLE
apple website clone

### PR DESCRIPTION
**Pull request by jabichris**
#### What does this PR do?

This PR will merge to master the whole implementation of the apple clone page.

### CODE REVIEW

**Comment by izaiasneto4** [comment]
### Hi @jabichris. Great work so far! Let's just fix this last thing so we can get your project approved. :arrow_down: 

- [ ] We need to fix the display of your website, it looks broken on my screen (I've tested it in both firefox and chrome and it still looks the same) 
image
Here, the background image it's not being displaying in its entirety and neither is the whole content. Also, there's a big blank space between this section and the next one.

image
This section is being overlayed by the footer, let's fix try to fix it :wink: 

### Congrats on the hard work :muscle:. When finished with the changes submit the pr again for a new code review:pray: 

TSE: Izaias Neto

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Jabiro!

### Nice job! Project looks! :+1: 

But first of all, let's fix the next problems and we can move on.

Kidly recommended your readme file should be descriptive
screen

## [OPTIONAL]
Let`s fix the next situation. As you can see from the next screenshots your page is not full screen cause you was added this property width: 1440px; to billboard class



if you delete this property width: 1440px; your project will be better



With this property footer is not full screen

Without property width: 1440px; it should be full screen


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes

**Comment by jabichris** [comment]
@Anna-Myzukina Thank you for the feedback. I have reacted on them and have resubmitted

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Jabiro,
## Project looks amazing. Congratulation :+1: Approved.
Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
